# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

install:
  - git clone -b $TRAVIS_BRANCH https://github.com/boostorg/boost.git boost
  - cd boost
  - git submodule init libs/assert
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/predef
  - git submodule init libs/static_assert
  - git submodule init libs/type_traits
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - cd libs/core
  - git checkout -q $TRAVIS_COMMIT
  - cd ../..
  - ./bootstrap.sh
  - ./b2 headers

script:
  - TOOLSET=gcc,clang
  - if [ $TRAVIS_OS_NAME == osx ]; then TOOLSET=clang; fi
  - ./b2 libs/core/test toolset=$TOOLSET
