# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

install:
  - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost.git boost
  - cd boost
  - git submodule init libs/assert
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/predef
  - git submodule init libs/static_assert
  - git submodule init libs/type_traits
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - cd libs\core
  - git checkout -q %APPVEYOR_REPO_COMMIT%
  - cd ..\..
  - bootstrap
  - b2 headers

build: off

test_script:
  - b2 libs/core/test toolset=msvc-9.0,msvc-10.0,msvc-11.0,msvc-12.0
